### ISSUE TITLE
LWJGL2 requires java 6 to compile, which is no longer supported by macOS and does not have an m1-ARM64 version 

### ISSUE THREAD

**Issue by rinOfTheStars** [r58Playz/lwjgl2-m1#1]
Before attempting to set the compiler version to java 8 (the closest easily installed jdk for ARM macs), running `ant generate-all` would crash with:
```
[ERROR] Source option 6 is no longer supported. Use 7 or later.
[ERROR] Target option 6 is no longer supported. Use 7 or later.
...
BUILD FAILED
/Users/**[username removed for privacy]**/Desktop/m1-lwjgl2-comp/lwjgl2-m1/platform_build/build-generator.xml:71: Compile failed; see the compiler error output for details.

```
After (likely incorrectly) trying to update the JVM source and target options to JDK 8:
```
generate-openal:
[processor] Compiling 3 source files to /Users/**[username removed for privacy]**//Desktop/m1-lwjgl2-comp/lwjgl2-m1/bin
[processor] warning: [options] bootstrap class path not set in conjunction with -source 8
[processor] warning: Supported source version 'RELEASE_6' from annotation processor 'org.lwjgl.util.generator.GeneratorProcessor' less than -source '8'
[processor] 2 warnings
[processor] 
[processor] 
[processor] An annotation processor threw an uncaught exception.
[processor] Consult the following stack trace for details.
[processor] java.lang.RuntimeException: 
[processor] -- Failed to process template: org.lwjgl.openal.AL10 --
[processor] 	at org.lwjgl.util.generator.GeneratorProcessor.process(GeneratorProcessor.java:93)
[processor] 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1025)
[processor] 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:940)
[processor] 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1269)
[processor] 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1383)
[processor] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1261)
[processor] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:935)
[processor] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
[processor] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
[processor] 	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
[processor] 	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
[processor] Caused by: java.lang.RuntimeException: javax.annotation.processing.FilerException: Attempt to recreate a file for type org.lwjgl.openal.AL10
[processor] 	at org.lwjgl.util.generator.GeneratorVisitor.visitTypeAsInterface(GeneratorVisitor.java:331)
[processor] 	at org.lwjgl.util.generator.GeneratorVisitor.visitTypeAsInterface(GeneratorVisitor.java:60)
[processor] 	at java.compiler@16/javax.lang.model.util.ElementKindVisitor6.visitType(ElementKindVisitor6.java:157)
[processor] 	at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.accept(Symbol.java:1560)
[processor] 	at org.lwjgl.util.generator.GeneratorProcessor.process(GeneratorProcessor.java:85)
[processor] 	... 10 more
[processor] Caused by: javax.annotation.processing.FilerException: Attempt to recreate a file for type org.lwjgl.openal.AL10
[processor] 	at jdk.compiler/com.sun.tools.javac.processing.JavacFiler.checkNameAndExistence(JavacFiler.java:725)
[processor] 	at jdk.compiler/com.sun.tools.javac.processing.JavacFiler.createSourceOrClassFile(JavacFiler.java:490)
[processor] 	at jdk.compiler/com.sun.tools.javac.processing.JavacFiler.createSourceFile(JavacFiler.java:427)
[processor] 	at org.lwjgl.util.generator.GeneratorVisitor.visitTypeAsInterface(GeneratorVisitor.java:303)
[processor] 	... 14 more

BUILD FAILED
/Users/**[username removed for privacy]**//Desktop/m1-lwjgl2-comp/lwjgl2-m1/platform_build/build-generator.xml:71: Compile failed; see the compiler error output for details.

Total time: 0 seconds
```
I'm probably doing something wrong; but it'd probably be worthwhile to fix this on your end to at least use java 8 for compiling.

**Comment by r58Playz** [comment]
Fixed, use the latest commit.
